import { Archivo } from "./Archivo";

export class Persona{

    id: number; //autogenerated
    
    nombre : String;
    
    apellido: String;
    
    edad: number;
    
    domicilio: String;
    
    nombrePuesto: String;
    
    foto: Archivo ;

    descripcion:String;
    
    constructor(id:number ,nombre:String ,apellido:String ,edad:number ,
        domicilio:String ,nombrePuesto:String,descripcion:String,foto:Archivo){
            this.id=id;
            this.nombre=nombre
            this.apellido=apellido;
            this.edad=edad;
            this.domicilio=domicilio;
            this.nombrePuesto=nombrePuesto;
            this.descripcion=descripcion;
            this.foto=foto;    
    }

}